### ISSUE TITLE
Swallows errors

### ISSUE THREAD

**Issue by vweevers** [mcollina/cloneable-readable#1]
The use of [pump](https://github.com/mafintosh/pump) means errors on the source stream won't be re-emitted on the cloneable stream, or on clones. Because pump calls `destroy()` rather than `destroy(err)`. Is this by design?

Additionally, if you do add a error callback to pump [here](https://github.com/mcollina/cloneable-readable/blob/master/index.js#L46):

```js
function clonePiped (that) {
  if (--that._clonesCount === 0) {
    pump(that._original, that, function (err) {
      if (err) console.log(err)
    })
    that._original = undefined
  }
}
```

Then the tests reveal a few `[Error: stream.push() after EOF]`.

**Comment by mcollina** [comment]
I agree that this is a problem. What should be the right behavior?

clone is destroyed -> nothing happens to the other clones, or the `Cloneable`
all clones are destroyed -> the `Cloneable` gets destroyed as well
`Cloneable` (or the cloned) errors -> all clones errors
a clone error -> nothing happens to `Cloneable`

Would you like to send a PR?
