### ISSUE TITLE
Error in stream not surfaced correctly

### ISSUE THREAD

**Issue by phated** [mcollina/cloneable-readable#18]
Hey @mcollina!  I've been working with this a bunch recently and I think I ran into an issue where an error in the Readable stream wrapped by this module won't be surfaced correctly to something like `stream.pipeline()`.

I've created a reproduction at https://github.com/phated/cloneable-readable-error-bug - would you have some time to point me in the right direction on this?

**Comment by mcollina** [comment]
I have no clue! I’ll look into this as soon as I get the chance.

As for tip into debugging things, I’ll try to reproduce without the from2 module, just to remove one piece of the puzzle.
