### ISSUE TITLE
Bug: isCloneable using instanceof

### ISSUE THREAD

**Issue by CodeMan99** [mcollina/cloneable-readable#23]
Issue: isCloneable returns false even if the passed in stream is a Cloneable instance
Cause: a single project loading more than a single version of this module

To reproduce:

1. Install `vinyl@2.2.0`.
2. Install `cloneable-readable@2.0.1`
3. Create a vinyl instance. The result of `cloneable.isCloneable(file.contents)` is false.

**Comment by mcollina** [comment]
That's not actually a bug, but a measure the prevent bugs in your code. We use `instanceof` because we rely on some internals. You'll have to use the same version `vinyl` uses.
