### ISSUE TITLE
How to pass a cloned stream to multiple functions that return a promise

### ISSUE THREAD

**Issue by kaykhan** [mcollina/cloneable-readable#25]
I have a stream which is an image. I want to upload the image to s3 and also upload the image to a different third party service.

```
describe("StorageModule", () => {

    let stream;
 
    it("should upload file to s3", async () => {

        const s3storageModule = new StorageModule();

        imageStream = cloneable(fs.createReadStream(process.cwd() + "/test/resources/" + "id/front.jpg"));

        const response = await s3storageModule.upload(key, imageStream.clone());

        expect(response.Location).to.equal(`${s3BaseUrl}/${key}`)

    });


    it("should submit image to 3rd party", async () => {

        const response = await sessionServie.document(imageStream.clone());
        expect(response.status).equal(202);

    });
});
```

Above i have 2 test cases the first submits the stream to s3 and the second submits a clone of the stream to the third party service that returns a promise.  

However the second test fails with 

>    Error: already started
>       at Cloneable.clone (node_modules/cloneable-readable/index.js:48:11)

**Comment by mcollina** [comment]
That will not be possible as the stream is already consumed when the first test finishes. If you want to do something like that, the two test would have to be executed in parallel.

**Comment by kaykhan** [comment]
How do i clone the stream and pass it to 2 separate functions? without having to do it in parallel

**Comment by mcollina** [comment]
You can clone a stream before it starts. Create all your clones and pass them around, they will all start at the same time.
