### ISSUE TITLE
Cloned stream will not pipe

### ISSUE THREAD

**Issue by perrin4869** [mcollina/cloneable-readable#27]
I created a small reproduction of a potential problem I found:

```js
const { createReadStream } = require('fs');
const { join } = require('path');

const cloneable = require('cloneable-readable');

const path = join(__dirname, 'index.html');
const original = createReadStream(path);
const stream = cloneable(original);
stream.clone();
stream.pipe(process.stdout); // will not pipe unless clone is removed
original.pipe(process.stdout); // will pipe
```

In the snippet above, I expect `stream.pipe(process.stdout)` to print the contents of `index.html`.
It does so only if we remove `stream.clone()` right above it.
`original.pipe(process.stdout)` will still print.
I find this behavior weird because none of the streams have begun being consumed yet, only `clone` has been called... I am not sure if I am missing something or if this is a bug. The example at the top of the `README.md` would suggest that my expected behavior is the correct one though.
Thanks!

**Comment by vweevers** [comment]
`stream.clone()` returns a stream, if you don't consume that (or any other clone) the flow won't start.

**Comment by mcollina** [comment]
As @vweevers said.

**Comment by perrin4869** [comment]
Hm... I still don't understand why the original cloneable `stream` won't output anything to `stdout` unless its clone is consumed first.

```js
// This will print the contents twice
stream.clone().pipe(process.stdout);
stream.pipe(process.stdout);
```

```js
// This will print the contents zero times
stream.clone();
stream.pipe(process.stdout);
```

```js
// Interestingly, this will also print the contents one time
// Why does the asynchronicity make a difference with the first case?
stream.clone().pipe(process.stdout);
setTimeout(() => {
  stream.pipe(process.stdout); // will not pipe
}, 1000);
```

Trying to update some of my `gulp` plugins I ran into these issues like `gulp-xml-transformer`.
I can confirm that replacing `setImmediate` with `setTimeout` of 1 second in the example in README.md will result in no content output to `out2`:

```js
'use strict'

var cloneable = require('cloneable-readable')
var fs = require('fs')
var pump = require('pump')

var stream = cloneable(fs.createReadStream('./package.json'))

pump(stream.clone(), fs.createWriteStream('./out1'))

// simulate some asynchronicity
setTimeout(function () {
  pump(stream, fs.createWriteStream('./out2')) // out2 is empty
}, 1000)
```

I will be very grateful if you can explain this behavior in more detail!

**Comment by perrin4869** [comment]
Or point to relevant documentation

**Comment by mcollina** [comment]
You can’t clone a stream of data. Once a data is emitted, it is lost unless it’s stored somewhere.

This module clone the object that represent the stream, so you can pass it safely across multiple functions etc. However, the data itself is not cloned or buffered, so all cloned streams progress at the same time.

If you want to buffer the data, do so explicitly, read it all and store it in a variable.

**Comment by perrin4869** [comment]
Hm, I think I got what is happening:

```js
const { createReadStream } = require('fs');
const { join } = require('path');
const cloneable = require('cloneable-readable');

const path = join(__dirname, 'index.html');
const stream = cloneable(createReadStream(path));

stream.on('resume', () => console.log('resumed!'));
stream.clone();
```

Calling `clone` will automatically, immediately resume a stream?

A little bit more context on what I am trying to do, very greatful for any advise!
I got these plugins like `gulp-html2pug`:

https://github.com/dotcore64/gulp-html2pug/blob/9f0d759074ed5ed978d08122b985b31b867ab94c/src/index.js#L19

I am using a module that I also wrote, `vinyl-contents-tostring` to read the original contents (an html file in this case), convert them, then inject them into a new `Vinyl` object. This new `Vinyl` object is cloned before its contents are read, and therefore `vinyl-contents-tostring` never resolves. I am thinking that the best solution would be to clone the contents before reading:

https://github.com/dotcore64/vinyl-contents-tostring/blob/fcd8d7097111cf38258574c92ca9286b3a489226/src/index.js#L9

Change that line to: `streamToString(file.contents.clone(), enc)`.
I tested the solution and it seems to work, but I am still not sure if it is the right approach.
Thanks you so much!

**Comment by phated** [comment]
@perrin4869 it looks like you are just overcomplicating things to the extreme. I have no idea what you are trying to do. You almost never want to clone a vinyl object.

**Comment by perrin4869** [comment]
@phated yeah lol I've been known to do that :P 
Wanted to clone the vinyl object just to keep the original intact, reduce the possibility of interference with other plugins, however unlikely. Actually, it would be useful if `Vinyl.clone` accepted overrides for the different properties, but that's another story.
Look how concise the plugin becomes otherwise though!
I'll remove the cloning part since it adds more headaches than is worth considering
