### ISSUE TITLE
Get a clone readable stream without WriteStream target

### ISSUE THREAD

**Issue by sboudouk** [mcollina/cloneable-readable#45]
Hey,

Is there a way to get the readable stream without any write stream target ?

**Comment by mcollina** [comment]
I don't understand the question.

**Comment by sboudouk** [comment]
Sorry i'll try to provide with more information, I'm currently using streams to upload file to my S3 using the `@aws-sdk/client-s3` package.

Just as an example, here's an example of how I use it:


```
    body = fs.createReadStream(filePath),

    let command: PutObjectCommandInput = {
      Bucket: this.bucketName,
      Key: fileKey,
      Body: body,
    };

     // this function use the s3 client to send the command
    await this.send(command);
```

So I provide `body` that is of type `fs.ReadStream`. From my understanding of this package, it seems like I need to pipe the cloned stream into a writeable stream.

My question is: Is it possible to get a cloned readable stream that I can provide in the `PutObjectCommandInput` ?

Hope it's clearer 😅

**Comment by mcollina** [comment]
Sure, this would work. Internally the aws client will start the stream.

**Comment by sboudouk** [comment]
Yes but, I can't get a Readable stream using the clone method :

```
var stream = cloneable(fs.createReadStream('./package.json'))

    let command: PutObjectCommandInput = {
      Bucket: this.bucketName,
      Key: fileKey,
      Body: stream.clone(),
    };
    
```

I would expect this to work but it does not, I am using it correctly ?

**Comment by mcollina** [comment]
you need to flow both streams.

**Comment by sboudouk** [comment]
I did not find how to do this unfortunately so I'm just recreating the stream manually with `fs.createReadStream` using the `ReadStream.path`
